[package]
name = "search_engine"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true

[dependencies]
tokio.workspace = true
futures.workspace = true

anyhow.workspace = true
sqlx.workspace = true
pgvector.workspace = true

ort.workspace = true
tokenizers.workspace = true

search_types = { path = "../search_types" }

siglip2 = { path = "../siglip2" }
dinov3 = { path = "../dinov3" }

parking_lot.workspace = true
dotenvy.workspace = true

[features]
default = []
serde = ["search_types/serde"]
