[package]
name = "app"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true

[dependencies]
leptos = { version = "0.8", features = ["nightly"] }
leptos_meta = { version = "0.8", features = [] }
leptos_router = { version = "0.8", features = ["nightly"] }
leptos-use = { version = "0.18", default-features = false, features = [
    "use_intersection_observer", "use_element_size", "signal_debounced", "use_window_scroll"
] }

search_types = { path = "../../search_types", features = ["serde"] }

serde.workspace = true
serde_json = "1"
urlencoding = "2"

wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
    "EventSource", "MessageEvent", "Element",
    "IntersectionObserver", "IntersectionObserverEntry", "IntersectionObserverInit",
    "ScrollToOptions", "ScrollBehavior", "Window", "DomRect", "CanvasRenderingContext2d",
    "ImageBitmap", "FileList", "File", "Touch", "TouchEvent", "TouchList"
] }

tokio = { workspace = true, optional = true }
search_engine = { path = "../../search_engine", optional = true, features = ["serde"] }
axum = { workspace = true, optional = true, features = ["macros"] }
leptos_axum = { version = "0.8", optional = true }
futures = { workspace = true, optional = true }
base64 = { version = "0.22", optional = true }

[features]
default = []
hydrate = ["leptos/hydrate"]
ssr = ["leptos/ssr", "leptos_meta/ssr", "leptos_router/ssr", "leptos-use/ssr", "dep:tokio", "dep:search_engine", "dep:axum", "dep:leptos_axum", "dep:futures", "dep:base64"]
