[package]
name = "app"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true

[dependencies]
leptos = { version = "0.8", features = ["nightly"] }
leptos_meta = { version = "0.8", features = [] }
leptos_router = { version = "0.8", features = ["nightly"] }
leptos-use = { version = "0.18", default-features = false, features = [] }
serde.workspace = true

[features]
default = []
hydrate = ["leptos/hydrate"]
ssr = ["leptos/ssr", "leptos_meta/ssr", "leptos_router/ssr", "leptos-use/ssr"]
