[package]
name = "wd_tagger"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true

[dependencies]
anyhow.workspace = true
image.workspace = true
fast_image_resize.workspace = true
csv = "1.4"

[target.'cfg(target_os = "macos")'.dependencies]
ort = { workspace = true, features = ["webgpu", "coreml"] }

[target.'cfg(not(target_os = "macos"))'.dependencies]
ort = { workspace = true, features = ["cuda", "tensorrt"] }
