[workspace]
members = [
    "db",
    "wd_tagger",
    "siglip2",
    "dinov3",
    "embed",
    "search_engine",
    "search/app",
    "search/frontend",
    "search/server",
    "search_types",
]
resolver = "3"

[workspace.package]
edition = "2024"
authors = ["Louis <836250617@qq.com>"]
license = "MIT"
repository = "https://github.com/kingwingfly/lets_embed"
documentation = "https://github.com/kingwingfly/lets_embed"

[workspace.dependencies]
# runtime
tokio = { version = "1", default-features = false, features = ["rt-multi-thread", "parking_lot", "macros"] }
futures = "0.3"
tokio-util = "0.7"
tokio-stream = { version = "0.1", features = ["io-util"] }
tokio-retry = "0.3"
ort = { version = "2.0.0-rc.12", features = ["load-dynamic"] }
# observability
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
# error
anyhow = "1.0"
# serde
serde = { version = "1", features = ["derive"] }
serde_json = "1"
# data structure
dashmap = "6.1"
bytes = "1.11"
# http
url = "2.5"
# db
sqlx = { version = "0.9", features = ["runtime-tokio", "postgres", "macros", "derive", "migrate"] }
pgvector = { version = "0.4", features = ["sqlx", "halfvec"] }
# util
tokenizers = "0.23"
image = "0.25"
fast_image_resize = { version = "6.0", features = ["image"] }
rayon = "1.12"
parking_lot = "0.12"
clap = { version = "4.6", features = ["derive"] }
sanitize-filename = "0.6"

[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"

[[workspace.metadata.leptos]]
name = "search"
site-addr = "0.0.0.0:3000"

tailwind-input-file = "search/style/tailwind.css"

bin-package = "server"
lib-package = "frontend"
bin-features = []
lib-features = []
lib-profile-release = "wasm-release"
