[package]
name = "gateway"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true

[dependencies]
pingora = { version = "0.8.0", features = ["proxy"] }
async-trait = "0.1"
http = "1.4"

anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

reqwest = { version = "0.13", optional = true, features = ["json", "blocking"] }
serde.workspace = true
serde_json.workspace = true
arc-swap = { version = "1.9", optional = true }
aws-lc-rs = { version = "1.17", optional = true }
base64 = { version = "0.22", optional = true }

[features]
default = []
validate-jwt = ["dep:reqwest", "dep:arc-swap", "dep:aws-lc-rs", "dep:base64"]
