name = "gateway-worker"
main = "build/index.js"
compatibility_date = "2026-06-01"

[build]
command = "cargo install -q \"worker-build@^0.8\" && worker-build --profile wasm-release"

[observability.logs]
enabled = true
invocation_logs = true

[[secrets_store_secrets]]
binding = "lets-embed-client-id"
store_id = "93d561f5fef7447eb3e1fd77e6445903"
secret_name = "lets-embed-client-id"

[[secrets_store_secrets]]
binding = "lets-embed-client-secret"
store_id = "93d561f5fef7447eb3e1fd77e6445903"
secret_name = "lets-embed-client-secret"

[[secrets_store_secrets]]
binding = "lets-embed-jwt-secret"
store_id = "93d561f5fef7447eb3e1fd77e6445903"
secret_name = "lets-embed-jwt-secret"

[[services]]
binding = "USER_WORKER"
service = "user-worker"

[durable_objects]
bindings = [{ name = "USER_ACCOUNT", class_name = "UserAccount", script_name = "user-worker" }]
