[package]
name = "img2webp"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
bytes = "1.11.1"
dotenvy = "0.15"
futures = "0.3"
libvips = "2.1"
opendal = { version = "0.57", features = ["services-s3", "services-fs"] }
tokio = { version = "1.52", features = ["full"] }
tokio-util = "0.7.18"
