[package]
name = "server"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true

[dependencies]
anyhow.workspace = true
futures.workspace = true
tokio.workspace = true

search_engine = { path = "../../search_engine" }

tracing.workspace = true
tracing-subscriber.workspace = true

axum = { workspace = true, features = ["tokio", "tracing", "http1"] }
leptos_axum = { version = "0.8" }
tower-http = { version = "0.6", features = ["fs", "trace"] }
async-stream = "0.3"

leptos = { version = "0.8", features = ["nightly", "ssr"] }
app = { path = "../app", features = ["ssr"] }

clap.workspace = true
serde.workspace = true
