[package]
name = "server"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true

[dependencies]
anyhow.workspace = true
futures.workspace = true
tokio.workspace = true

axum = { version = "0.8" }
leptos_axum = { version = "0.8" }

leptos = { version = "0.8", features = ["nightly", "ssr"] }
app = { path = "../app", features = ["ssr"] }
