[package]
name = "db"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true

[dev-dependencies]
anyhow.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
futures.workspace = true
sqlx.workspace = true
struson = { version = "0.7", features = ["simple-api"] }
yaml_serde = "0.10"
serde.workspace = true
